/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions.route'
import { Route as SignUpRouteImport } from './routes/signUp.route'
import { Route as SignInRouteImport } from './routes/signIn.route'
import { Route as HomeRouteImport } from './routes/home.route'
import { Route as AboutRouteImport } from './routes/about.route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TransactionsRouteRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRoute,
} as any)

const SignUpRouteRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRoute,
} as any)

const SignInRouteRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRoute,
} as any)

const HomeRouteRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRoute
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRoute
    }
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
  '/signIn': typeof SignInRouteRoute
  '/signUp': typeof SignUpRouteRoute
  '/transactions': typeof TransactionsRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
  '/signIn': typeof SignInRouteRoute
  '/signUp': typeof SignUpRouteRoute
  '/transactions': typeof TransactionsRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/home': typeof HomeRouteRoute
  '/signIn': typeof SignInRouteRoute
  '/signUp': typeof SignUpRouteRoute
  '/transactions': typeof TransactionsRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/home' | '/signIn' | '/signUp' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/home' | '/signIn' | '/signUp' | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/home'
    | '/signIn'
    | '/signUp'
    | '/transactions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
  SignInRouteRoute: typeof SignInRouteRoute
  SignUpRouteRoute: typeof SignUpRouteRoute
  TransactionsRouteRoute: typeof TransactionsRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
  SignInRouteRoute: SignInRouteRoute,
  SignUpRouteRoute: SignUpRouteRoute,
  TransactionsRouteRoute: TransactionsRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/home",
        "/signIn",
        "/signUp",
        "/transactions"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/about": {
      "filePath": "about.route.tsx"
    },
    "/home": {
      "filePath": "home.route.tsx"
    },
    "/signIn": {
      "filePath": "signIn.route.tsx"
    },
    "/signUp": {
      "filePath": "signUp.route.tsx"
    },
    "/transactions": {
      "filePath": "transactions.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
