/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions.route'
import { Route as SignUpRouteImport } from './routes/signUp.route'
import { Route as SignInRouteImport } from './routes/signIn.route'
import { Route as SalaryRouteImport } from './routes/salary.route'
import { Route as HomeRouteImport } from './routes/home.route'
import { Route as AdviceRouteImport } from './routes/advice.route'
import { Route as AboutRouteImport } from './routes/about.route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TransactionsRouteRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRoute,
} as any)

const SignUpRouteRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRoute,
} as any)

const SignInRouteRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRoute,
} as any)

const SalaryRouteRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRoute,
} as any)

const HomeRouteRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AdviceRouteRoute = AdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => rootRoute,
} as any)

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/advice': {
      id: '/advice'
      path: '/advice'
      fullPath: '/advice'
      preLoaderRoute: typeof AdviceRouteImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRoute
    }
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRoute
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRoute
    }
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/advice': typeof AdviceRouteRoute
  '/home': typeof HomeRouteRoute
  '/salary': typeof SalaryRouteRoute
  '/signIn': typeof SignInRouteRoute
  '/signUp': typeof SignUpRouteRoute
  '/transactions': typeof TransactionsRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/advice': typeof AdviceRouteRoute
  '/home': typeof HomeRouteRoute
  '/salary': typeof SalaryRouteRoute
  '/signIn': typeof SignInRouteRoute
  '/signUp': typeof SignUpRouteRoute
  '/transactions': typeof TransactionsRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/advice': typeof AdviceRouteRoute
  '/home': typeof HomeRouteRoute
  '/salary': typeof SalaryRouteRoute
  '/signIn': typeof SignInRouteRoute
  '/signUp': typeof SignUpRouteRoute
  '/transactions': typeof TransactionsRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advice'
    | '/home'
    | '/salary'
    | '/signIn'
    | '/signUp'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advice'
    | '/home'
    | '/salary'
    | '/signIn'
    | '/signUp'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advice'
    | '/home'
    | '/salary'
    | '/signIn'
    | '/signUp'
    | '/transactions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRoute
  AdviceRouteRoute: typeof AdviceRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
  SalaryRouteRoute: typeof SalaryRouteRoute
  SignInRouteRoute: typeof SignInRouteRoute
  SignUpRouteRoute: typeof SignUpRouteRoute
  TransactionsRouteRoute: typeof TransactionsRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRoute,
  AdviceRouteRoute: AdviceRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
  SalaryRouteRoute: SalaryRouteRoute,
  SignInRouteRoute: SignInRouteRoute,
  SignUpRouteRoute: SignUpRouteRoute,
  TransactionsRouteRoute: TransactionsRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/advice",
        "/home",
        "/salary",
        "/signIn",
        "/signUp",
        "/transactions"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/about": {
      "filePath": "about.route.tsx"
    },
    "/advice": {
      "filePath": "advice.route.tsx"
    },
    "/home": {
      "filePath": "home.route.tsx"
    },
    "/salary": {
      "filePath": "salary.route.tsx"
    },
    "/signIn": {
      "filePath": "signIn.route.tsx"
    },
    "/signUp": {
      "filePath": "signUp.route.tsx"
    },
    "/transactions": {
      "filePath": "transactions.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
